
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Programs/Cmake/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:24 (project)"
    message: |
      The system is: Windows - 10.0.22000 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/Programs/Cmake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Programs/Cmake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Programs/Cmake/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:24 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.6.3+07e294721 for .NET Framework
      Сборка начата 24.05.2023 16:02:07.
      
      Проект "D:\\repo\\VST\\AudioPlugSharp-0.4\\vstbuild\\CMakeFiles\\3.26.4\\CompilerIdC\\CompilerIdC.vcxproj" в узле 1 (целевые объекты по умолчанию).
      PrepareForBuild:
        Создание каталога "Debug\\".
        Создание каталога "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Создание "Debug\\CompilerIdC.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
      ClCompile:
        D:\\VS22\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        D:\\VS22\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> D:\\repo\\VST\\AudioPlugSharp-0.4\\vstbuild\\CMakeFiles\\3.26.4\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=D:\\VS22\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Файл "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" удаляется.
        Обращение к "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Сборка проекта "D:\\repo\\VST\\AudioPlugSharp-0.4\\vstbuild\\CMakeFiles\\3.26.4\\CompilerIdC\\CompilerIdC.vcxproj" завершена (целевые объекты по умолчанию).
      
      Сборка успешно завершена.
          Предупреждений: 0
          Ошибок: 0
      
      Прошло времени 00:00:03.37
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        D:/repo/VST/AudioPlugSharp-0.4/vstbuild/CMakeFiles/3.26.4/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/Programs/Cmake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Programs/Cmake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Programs/Cmake/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:24 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.6.3+07e294721 for .NET Framework
      Сборка начата 24.05.2023 16:02:11.
      
      Проект "D:\\repo\\VST\\AudioPlugSharp-0.4\\vstbuild\\CMakeFiles\\3.26.4\\CompilerIdCXX\\CompilerIdCXX.vcxproj" в узле 1 (целевые объекты по умолчанию).
      PrepareForBuild:
        Создание каталога "Debug\\".
        Создание каталога "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Создание "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
      ClCompile:
        D:\\VS22\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        D:\\VS22\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> D:\\repo\\VST\\AudioPlugSharp-0.4\\vstbuild\\CMakeFiles\\3.26.4\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=D:\\VS22\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Файл "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" удаляется.
        Обращение к "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Сборка проекта "D:\\repo\\VST\\AudioPlugSharp-0.4\\vstbuild\\CMakeFiles\\3.26.4\\CompilerIdCXX\\CompilerIdCXX.vcxproj" завершена (целевые объекты по умолчанию).
      
      Сборка успешно завершена.
          Предупреждений: 0
          Ошибок: 0
      
      Прошло времени 00:00:01.04
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        D:/repo/VST/AudioPlugSharp-0.4/vstbuild/CMakeFiles/3.26.4/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Programs/Cmake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/Programs/Cmake/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:24 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/repo/VST/AudioPlugSharp-0.4/vstbuild/CMakeFiles/CMakeScratch/TryCompile-cuvc0k"
      binary: "D:/repo/VST/AudioPlugSharp-0.4/vstbuild/CMakeFiles/CMakeScratch/TryCompile-cuvc0k"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      CMAKE_MODULE_PATH: "D:/repo/VST/AudioPlugSharp-0.4/vst3sdk/cmake/modules"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: D:/repo/VST/AudioPlugSharp-0.4/vstbuild/CMakeFiles/CMakeScratch/TryCompile-cuvc0k
        
        Run Build Command(s):D:/VS22/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_7d76f.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.6.3+07e294721 for .NET Framework
        Сборка начата 24.05.2023 16:02:13.
        
        Проект "D:\\repo\\VST\\AudioPlugSharp-0.4\\vstbuild\\CMakeFiles\\CMakeScratch\\TryCompile-cuvc0k\\cmTC_7d76f.vcxproj" в узле 1 (целевые объекты по умолчанию).
        PrepareForBuild:
          Создание каталога "cmTC_7d76f.dir\\Debug\\".
          Создание каталога "D:\\repo\\VST\\AudioPlugSharp-0.4\\vstbuild\\CMakeFiles\\CMakeScratch\\TryCompile-cuvc0k\\Debug\\".
          Создание каталога "cmTC_7d76f.dir\\Debug\\cmTC_7d76f.tlog\\".
        InitializeBuildStatus:
          Создание "cmTC_7d76f.dir\\Debug\\cmTC_7d76f.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
        ClCompile:
          D:\\VS22\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_7d76f.dir\\Debug\\\\" /Fd"cmTC_7d76f.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "D:\\Programs\\Cmake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
          Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.36.32532 для x64
          CMakeCCompilerABI.c
          (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_7d76f.dir\\Debug\\\\" /Fd"cmTC_7d76f.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "D:\\Programs\\Cmake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
        Link:
          D:\\VS22\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\repo\\VST\\AudioPlugSharp-0.4\\vstbuild\\CMakeFiles\\CMakeScratch\\TryCompile-cuvc0k\\Debug\\cmTC_7d76f.exe" /INCREMENTAL /ILK:"cmTC_7d76f.dir\\Debug\\cmTC_7d76f.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/repo/VST/AudioPlugSharp-0.4/vstbuild/CMakeFiles/CMakeScratch/TryCompile-cuvc0k/Debug/cmTC_7d76f.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/repo/VST/AudioPlugSharp-0.4/vstbuild/CMakeFiles/CMakeScratch/TryCompile-cuvc0k/Debug/cmTC_7d76f.lib" /MACHINE:X64  /machine:x64 cmTC_7d76f.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_7d76f.vcxproj -> D:\\repo\\VST\\AudioPlugSharp-0.4\\vstbuild\\CMakeFiles\\CMakeScratch\\TryCompile-cuvc0k\\Debug\\cmTC_7d76f.exe
        FinalizeBuildStatus:
          Файл "cmTC_7d76f.dir\\Debug\\cmTC_7d76f.tlog\\unsuccessfulbuild" удаляется.
          Обращение к "cmTC_7d76f.dir\\Debug\\cmTC_7d76f.tlog\\cmTC_7d76f.lastbuildstate".
        Сборка проекта "D:\\repo\\VST\\AudioPlugSharp-0.4\\vstbuild\\CMakeFiles\\CMakeScratch\\TryCompile-cuvc0k\\cmTC_7d76f.vcxproj" завершена (целевые объекты по умолчанию).
        
        Сборка успешно завершена.
            Предупреждений: 0
            Ошибок: 0
        
        Прошло времени 00:00:00.99
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Programs/Cmake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/Programs/Cmake/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:24 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/repo/VST/AudioPlugSharp-0.4/vstbuild/CMakeFiles/CMakeScratch/TryCompile-0dx1ss"
      binary: "D:/repo/VST/AudioPlugSharp-0.4/vstbuild/CMakeFiles/CMakeScratch/TryCompile-0dx1ss"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      CMAKE_MODULE_PATH: "D:/repo/VST/AudioPlugSharp-0.4/vst3sdk/cmake/modules"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: D:/repo/VST/AudioPlugSharp-0.4/vstbuild/CMakeFiles/CMakeScratch/TryCompile-0dx1ss
        
        Run Build Command(s):D:/VS22/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_678f4.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.6.3+07e294721 for .NET Framework
        Сборка начата 24.05.2023 16:02:14.
        
        Проект "D:\\repo\\VST\\AudioPlugSharp-0.4\\vstbuild\\CMakeFiles\\CMakeScratch\\TryCompile-0dx1ss\\cmTC_678f4.vcxproj" в узле 1 (целевые объекты по умолчанию).
        PrepareForBuild:
          Создание каталога "cmTC_678f4.dir\\Debug\\".
          Создание каталога "D:\\repo\\VST\\AudioPlugSharp-0.4\\vstbuild\\CMakeFiles\\CMakeScratch\\TryCompile-0dx1ss\\Debug\\".
          Создание каталога "cmTC_678f4.dir\\Debug\\cmTC_678f4.tlog\\".
        InitializeBuildStatus:
          Создание "cmTC_678f4.dir\\Debug\\cmTC_678f4.tlog\\unsuccessfulbuild", так как было задано "AlwaysCreate".
        ClCompile:
          D:\\VS22\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_678f4.dir\\Debug\\\\" /Fd"cmTC_678f4.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "D:\\Programs\\Cmake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
          Оптимизирующий компилятор Microsoft (R) C/C++ версии 19.36.32532 для x64
          CMakeCXXCompilerABI.cpp
          (C) Корпорация Майкрософт (Microsoft Corporation).  Все права защищены.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_678f4.dir\\Debug\\\\" /Fd"cmTC_678f4.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "D:\\Programs\\Cmake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          D:\\VS22\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\repo\\VST\\AudioPlugSharp-0.4\\vstbuild\\CMakeFiles\\CMakeScratch\\TryCompile-0dx1ss\\Debug\\cmTC_678f4.exe" /INCREMENTAL /ILK:"cmTC_678f4.dir\\Debug\\cmTC_678f4.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/repo/VST/AudioPlugSharp-0.4/vstbuild/CMakeFiles/CMakeScratch/TryCompile-0dx1ss/Debug/cmTC_678f4.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/repo/VST/AudioPlugSharp-0.4/vstbuild/CMakeFiles/CMakeScratch/TryCompile-0dx1ss/Debug/cmTC_678f4.lib" /MACHINE:X64  /machine:x64 cmTC_678f4.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_678f4.vcxproj -> D:\\repo\\VST\\AudioPlugSharp-0.4\\vstbuild\\CMakeFiles\\CMakeScratch\\TryCompile-0dx1ss\\Debug\\cmTC_678f4.exe
        FinalizeBuildStatus:
          Файл "cmTC_678f4.dir\\Debug\\cmTC_678f4.tlog\\unsuccessfulbuild" удаляется.
          Обращение к "cmTC_678f4.dir\\Debug\\cmTC_678f4.tlog\\cmTC_678f4.lastbuildstate".
        Сборка проекта "D:\\repo\\VST\\AudioPlugSharp-0.4\\vstbuild\\CMakeFiles\\CMakeScratch\\TryCompile-0dx1ss\\cmTC_678f4.vcxproj" завершена (целевые объекты по умолчанию).
        
        Сборка успешно завершена.
            Предупреждений: 0
            Ошибок: 0
        
        Прошло времени 00:00:00.85
        
      exitCode: 0
...
